name: Mover archivos a API

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  move-to-api-repo:
    runs-on: ubuntu-latest
    steps:
      # Chequear el código del repositorio principal
      - name: Checkout principal repo
        uses: actions/checkout@v4
        with:
          repository: YoharJB/API
          token: ${{ secrets.BOT }}
          ref: main

      # Chequear el código del repositorio de API
      - name: Checkout repo API-RAW
        uses: actions/checkout@v4
        with:
          repository: YoharJB/API-RAW
          token: ${{ secrets.BOT }}
          path: API-RAW
          ref: main

      # Mover los archivos
      - name: Mover archivos
        run: |
          # Usar rsync para mover y actualizar todos los archivos
          rsync -av ./API/Addons/ ./API-RAW/API/Addons/

      # Combinar contenido de JSONs
      # Combinar contenido de JSONs
      - name: Combinar JSONs
        run: |
          # Directorio y archivo JSON del destino
          DEST_MADDONS_JSON="./API-RAW/API/Maddons.json"

          # Crear un archivo temporal para combinar todos los JSONs
          TEMP_JSON="./temp_combined.json"
          echo "[]" > "$TEMP_JSON"

          # Combinar todos los archivos JSON de la carpeta API
          find ./API -maxdepth 1 -name '*.json' | while read USER_JSON; do
            echo "Procesando JSON del usuario: $USER_JSON"
            jq -s '.[0] + .[1]' "$TEMP_JSON" "$USER_JSON" > "./temp_combined_updated.json"
            mv "./temp_combined_updated.json" "$TEMP_JSON"
          done

          # Combinar el archivo temporal con el JSON destino
          jq -s '.[0] + .[1]' "$DEST_MADDONS_JSON" "$TEMP_JSON" > ./API-RAW/API/Maddons_updated.json

          # Reemplazar el archivo Maddons.json original
          mv ./API-RAW/API/Maddons_updated.json "$DEST_MADDONS_JSON"

          # Eliminar el archivo temporal
          rm -f "$TEMP_JSON"

      # Commit de los cambios en el repositorio de API-RAW
      - name: Commit y push cambios
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: "API-RAW"
          destination-github-username: YoharJB
          destination-repository-name: API-RAW
          user-email: "actions@github.com"
          user-name: "GitHub Actions"
        env:
          API_TOKEN_GITHUB: ${{ secrets.BOT }}

      # Eliminar archivos procesados en API
      - name: Eliminar archivos procesados
        run: |
          # Directorios específicos a limpiar
          TARGET_DIRS=(
            "./API/Addons/Lichking"
            "./API/Addons/Cataclysm"
            "./API/Addons/Pandaria"
            "./API/Addons/Vanilla"
            "./API/Addons/TBC"
          )
      
          # Limpiar contenido de las carpetas objetivo, eliminando solo los archivos con las extensiones indicadas
          for DIR in "${TARGET_DIRS[@]}"; do
            if [ -d "$DIR" ]; then
              find "$DIR" -type f \( -iname "*.webp" -o -iname "*.zip" -o -iname "*.md" -o -iname "*.json" \) -exec rm -f {} \;
            fi
          done

          # Eliminar el archivo .json en ./API
          find ./API -maxdepth 1 -name '*.json' -exec rm -f {} \;

      # Hacer commit de los cambios de limpieza en API
      - name: Commit cambios de limpieza
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Limpiar archivos procesados en API"
          git push
